### ISSUE TITLE
noiseParameters column optional

### ISSUE THREAD

**Issue by fbergmann** [ICB-DCM/PEtab#174]
According to the documentation[1] it seems that the noiseParameters column is optional, however `petablint` and pypesto import fail in this scenario with: 

```
Traceback (most recent call last):
  File "/home/user/.local/bin/petablint", line 11, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.6/site-packages/petab/petablint.py", line 127, in main
    ret = petab.lint.lint_problem(problem)
  File "/home/user/.local/lib/python3.6/site-packages/petab/lint.py", line 451, in lint_problem
    problem.measurement_df, problem.condition_df)
  File "/home/user/.local/lib/python3.6/site-packages/petab/lint.py", line 116, in check_parameter_df
    df, sbml_model, measurement_df, condition_df)
  File "/home/user/.local/lib/python3.6/site-packages/petab/lint.py", line 129, in assert_all_parameters_present_in_parameter_df
    measurement_df=measurement_df)
  File "/home/user/.local/lib/python3.6/site-packages/petab/core.py", line 760, in get_required_parameters_for_parameter_table
    split_parameter_replacement_list(row.noiseParameters))
  File "/home/user/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 5179, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'noiseParameters'
```

Creating the column without specifying a value, results in a `petablint` error message: 

```
No placeholders have been specified in the noise model SBML AssigmentRule for:
observableId                                         <name>
...
noiseParameters                                            NaN
Name: 0, dtype: object
But parameter name or multiple overrides were specified in the noiseParameters column.
Not OK
```

[1]: https://github.com/ICB-DCM/PEtab/blob/master/doc/documentation_data_format.md#measurement-table

**Comment by dweindl** [comment]
Hi Frank, sorry, overlooked that one. Thanks for reporting. Fixed in #192.
